# Google Analytics
google_analytics: G-0HYRRBTEVY

# Google Adsense
google_adsense: ca-pub-5831288475713424

# Cookie Compliance (cookie-script.com)
cookie_script_id: 2be5e82d68f0c53bc790ee87ffbd568c

repository: JackAce/jackace.com

title: JackAce
author: Jack Haze
avatar_url: https://en.gravatar.com/userimage/16333631/fd0ff7b3a6145af790737011dc6b2272.png?size=300
description: > # this means to ignore newlines until next section
  Gambling. Crypto. Math.
contact:
  url: https://github.com/JackAce

# Settings for Hamilton theme
avatar: https://en.gravatar.com/userimage/16333631/fd0ff7b3a6145af790737011dc6b2272.png?size=300
location: Southern California
skin: midnight
date_format: "%-d %b %Y"
email_privacy: privacy@jackace.com

# Subscribe Feed
# 
# By default, your site generates a subscription feed (RSS/Atom) at /feed.xml
# Uncomment the next two lines to change the path.
#feed:
#   path: /feed.xml

# Homepage
show_excerpts: true  # set to true to show excerpts on the homepage, otherwise full posts are shown

# Comments
# To enable comments, set the `enabled` field to true and supply either a Disqus short name or a Jekyll comments receiver
disqus: jackace
comments:
  enabled: true
  #show_count: true
  #receiver:

# Jekyll Settings
permalink: /blog/:year/:month/:day/:title/
paginate: 20
page_group_size: 5
paginate_path: "/archive/page/:num"
category_dir: categories

font-awesome:
  assets: true

# Build settings
markdown: kramdown
kramdown:
  hard_wrap: false
remote_theme: jackacestudios/jekyll-theme-hamilton

exclude: [README.md CODE_OF_CONDUCT.md script .gitattributes .gitignore keybase.txt RakeFile]
keep_files: [images demos code ads.txt robots.txt favicon.ico]
incremental: true

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
  #- jemoji
  #- jekyll-glossary_tooltip

